language: python
sudo: required
addons:
  firefox: "65.0.1"
before_script:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - tar -xvzf geckodriver*
  - chmod +x geckodriver
  - export PATH=$PATH:$PWD
  - sudo cp geckodriver /usr/local/bin/
  - sudo apt-get install xvfb
  - Xvfb :10 -ac &
  - export DISPLAY=:10

python:
- '3.6'
install:
- pip install -r requirements-travis.txt
env:
- DJANGO=2.1.7
script:
- python manage.py test
branches:
  only:
  - gh-pages
  - "/.*/"
