language: python
sudo: required
addons:
  chrome: stable
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
env:
- DJANGO=2.1.7
script:
- python manage.py test
branches:
  only:
  - gh-pages
  - "/.*/"
