language: python
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.3/bin/
  - export CHROME_BIN=chromium-browser
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
env:
- DJANGO=2.1.7
script:
- python manage.py test
branches:
  only:
  - gh-pages
  - "/.*/"
deploy:
  provider: heroku
  api_key:
    secure: XSfGvd6STwKXZ+QDGmtjiYRc1P1l46UGkdJIZc4EL4TUEW97Y16T0sYCIRfG8baP052xP2gMXTvsxsSsTqPC3d/vrZqheGNyjZOYY8rjJZALtzA73MRm38OlAm6p1/GunEd/sWs8QsF648sRICd1RHfzf4Q2kw1tId6lYdKOtsdFSEdbXHJBqnsNXVlHVScI+9MFqb9eOyfv46/H1KOTPRvPAzopcwAAWbFrmthVxb8TPCh9dBm01iNLx4AgkVYywi36Fyd2XEr71TFj0du8lHpS1PlxDIydCkD/mVxDvzmOTdx8LptfRZmcqo2oLZRb11WvShi/j0UJgdObgIhg2ZPIa341E2wslnmuVOHqhFEvuMhZ7jCi8k3Q7N/3RKk4l7pjUAktsa0WolA/eV786u/7xy8bgySRe6o6Wd/lcX3m3rnIlZ2LeAlmU+FoFWzaOdCXmrmT67sneBVvktpWl77K1G7GjnNAmfGFZJebtC3cgQTBR0Jc5v0aC/w3b8JTZ9SeDBdFKCEYTOXh6IhipegztZMYf3kR7h0N8GNnIvDjNAz5l+rJV+iuxDjgBzbrVZaIbpc8DSc0w1XyAjZ1hBf/ALCoX2fS5TchoUNxaKlaNmcA88IsdHYkhjX7gPrHJouCWCICXlJfWT1IsVFFFBs7m9kZlWWQ3A/dhbeDwfw=
  app: segfaulters3240
